# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/RevivalBCPL/RevivalBCPL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/RevivalBCPL/RevivalBCPL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/RevivalBCPL/RevivalBCPL/CMakeFiles /home/runner/work/RevivalBCPL/RevivalBCPL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/RevivalBCPL/RevivalBCPL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

AArch64Instructions.o: AArch64Instructions.cpp.o
.PHONY : AArch64Instructions.o

# target to build an object file
AArch64Instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/AArch64Instructions.cpp.o
.PHONY : AArch64Instructions.cpp.o

AArch64Instructions.i: AArch64Instructions.cpp.i
.PHONY : AArch64Instructions.i

# target to preprocess a source file
AArch64Instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/AArch64Instructions.cpp.i
.PHONY : AArch64Instructions.cpp.i

AArch64Instructions.s: AArch64Instructions.cpp.s
.PHONY : AArch64Instructions.s

# target to generate assembly for a file
AArch64Instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/AArch64Instructions.cpp.s
.PHONY : AArch64Instructions.cpp.s

CodeGenerator.o: CodeGenerator.cpp.o
.PHONY : CodeGenerator.o

# target to build an object file
CodeGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/CodeGenerator.cpp.o
.PHONY : CodeGenerator.cpp.o

CodeGenerator.i: CodeGenerator.cpp.i
.PHONY : CodeGenerator.i

# target to preprocess a source file
CodeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/CodeGenerator.cpp.i
.PHONY : CodeGenerator.cpp.i

CodeGenerator.s: CodeGenerator.cpp.s
.PHONY : CodeGenerator.s

# target to generate assembly for a file
CodeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/CodeGenerator.cpp.s
.PHONY : CodeGenerator.cpp.s

ConstantFoldingPass.o: ConstantFoldingPass.cpp.o
.PHONY : ConstantFoldingPass.o

# target to build an object file
ConstantFoldingPass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ConstantFoldingPass.cpp.o
.PHONY : ConstantFoldingPass.cpp.o

ConstantFoldingPass.i: ConstantFoldingPass.cpp.i
.PHONY : ConstantFoldingPass.i

# target to preprocess a source file
ConstantFoldingPass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ConstantFoldingPass.cpp.i
.PHONY : ConstantFoldingPass.cpp.i

ConstantFoldingPass.s: ConstantFoldingPass.cpp.s
.PHONY : ConstantFoldingPass.s

# target to generate assembly for a file
ConstantFoldingPass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ConstantFoldingPass.cpp.s
.PHONY : ConstantFoldingPass.cpp.s

DebugPrinter.o: DebugPrinter.cpp.o
.PHONY : DebugPrinter.o

# target to build an object file
DebugPrinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/DebugPrinter.cpp.o
.PHONY : DebugPrinter.cpp.o

DebugPrinter.i: DebugPrinter.cpp.i
.PHONY : DebugPrinter.i

# target to preprocess a source file
DebugPrinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/DebugPrinter.cpp.i
.PHONY : DebugPrinter.cpp.i

DebugPrinter.s: DebugPrinter.cpp.s
.PHONY : DebugPrinter.s

# target to generate assembly for a file
DebugPrinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/DebugPrinter.cpp.s
.PHONY : DebugPrinter.cpp.s

JitRuntime.o: JitRuntime.cpp.o
.PHONY : JitRuntime.o

# target to build an object file
JitRuntime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/JitRuntime.cpp.o
.PHONY : JitRuntime.cpp.o

JitRuntime.i: JitRuntime.cpp.i
.PHONY : JitRuntime.i

# target to preprocess a source file
JitRuntime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/JitRuntime.cpp.i
.PHONY : JitRuntime.cpp.i

JitRuntime.s: JitRuntime.cpp.s
.PHONY : JitRuntime.s

# target to generate assembly for a file
JitRuntime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/JitRuntime.cpp.s
.PHONY : JitRuntime.cpp.s

LabelManager.o: LabelManager.cpp.o
.PHONY : LabelManager.o

# target to build an object file
LabelManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LabelManager.cpp.o
.PHONY : LabelManager.cpp.o

LabelManager.i: LabelManager.cpp.i
.PHONY : LabelManager.i

# target to preprocess a source file
LabelManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LabelManager.cpp.i
.PHONY : LabelManager.cpp.i

LabelManager.s: LabelManager.cpp.s
.PHONY : LabelManager.s

# target to generate assembly for a file
LabelManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LabelManager.cpp.s
.PHONY : LabelManager.cpp.s

Lexer.o: Lexer.cpp.o
.PHONY : Lexer.o

# target to build an object file
Lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Lexer.cpp.o
.PHONY : Lexer.cpp.o

Lexer.i: Lexer.cpp.i
.PHONY : Lexer.i

# target to preprocess a source file
Lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Lexer.cpp.i
.PHONY : Lexer.cpp.i

Lexer.s: Lexer.cpp.s
.PHONY : Lexer.s

# target to generate assembly for a file
Lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Lexer.cpp.s
.PHONY : Lexer.cpp.s

LoopInvariantCodeMotionPass.o: LoopInvariantCodeMotionPass.cpp.o
.PHONY : LoopInvariantCodeMotionPass.o

# target to build an object file
LoopInvariantCodeMotionPass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopInvariantCodeMotionPass.cpp.o
.PHONY : LoopInvariantCodeMotionPass.cpp.o

LoopInvariantCodeMotionPass.i: LoopInvariantCodeMotionPass.cpp.i
.PHONY : LoopInvariantCodeMotionPass.i

# target to preprocess a source file
LoopInvariantCodeMotionPass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopInvariantCodeMotionPass.cpp.i
.PHONY : LoopInvariantCodeMotionPass.cpp.i

LoopInvariantCodeMotionPass.s: LoopInvariantCodeMotionPass.cpp.s
.PHONY : LoopInvariantCodeMotionPass.s

# target to generate assembly for a file
LoopInvariantCodeMotionPass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopInvariantCodeMotionPass.cpp.s
.PHONY : LoopInvariantCodeMotionPass.cpp.s

LoopOptimizer.o: LoopOptimizer.cpp.o
.PHONY : LoopOptimizer.o

# target to build an object file
LoopOptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopOptimizer.cpp.o
.PHONY : LoopOptimizer.cpp.o

LoopOptimizer.i: LoopOptimizer.cpp.i
.PHONY : LoopOptimizer.i

# target to preprocess a source file
LoopOptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopOptimizer.cpp.i
.PHONY : LoopOptimizer.cpp.i

LoopOptimizer.s: LoopOptimizer.cpp.s
.PHONY : LoopOptimizer.s

# target to generate assembly for a file
LoopOptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/LoopOptimizer.cpp.s
.PHONY : LoopOptimizer.cpp.s

Optimizer.o: Optimizer.cpp.o
.PHONY : Optimizer.o

# target to build an object file
Optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Optimizer.cpp.o
.PHONY : Optimizer.cpp.o

Optimizer.i: Optimizer.cpp.i
.PHONY : Optimizer.i

# target to preprocess a source file
Optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Optimizer.cpp.i
.PHONY : Optimizer.cpp.i

Optimizer.s: Optimizer.cpp.s
.PHONY : Optimizer.s

# target to generate assembly for a file
Optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Optimizer.cpp.s
.PHONY : Optimizer.cpp.s

Parser.o: Parser.cpp.o
.PHONY : Parser.o

# target to build an object file
Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Parser.cpp.o
.PHONY : Parser.cpp.o

Parser.i: Parser.cpp.i
.PHONY : Parser.i

# target to preprocess a source file
Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Parser.cpp.i
.PHONY : Parser.cpp.i

Parser.s: Parser.cpp.s
.PHONY : Parser.s

# target to generate assembly for a file
Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Parser.cpp.s
.PHONY : Parser.cpp.s

PassManager.o: PassManager.cpp.o
.PHONY : PassManager.o

# target to build an object file
PassManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/PassManager.cpp.o
.PHONY : PassManager.cpp.o

PassManager.i: PassManager.cpp.i
.PHONY : PassManager.i

# target to preprocess a source file
PassManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/PassManager.cpp.i
.PHONY : PassManager.cpp.i

PassManager.s: PassManager.cpp.s
.PHONY : PassManager.s

# target to generate assembly for a file
PassManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/PassManager.cpp.s
.PHONY : PassManager.cpp.s

Preprocessor.o: Preprocessor.cpp.o
.PHONY : Preprocessor.o

# target to build an object file
Preprocessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Preprocessor.cpp.o
.PHONY : Preprocessor.cpp.o

Preprocessor.i: Preprocessor.cpp.i
.PHONY : Preprocessor.i

# target to preprocess a source file
Preprocessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Preprocessor.cpp.i
.PHONY : Preprocessor.cpp.i

Preprocessor.s: Preprocessor.cpp.s
.PHONY : Preprocessor.s

# target to generate assembly for a file
Preprocessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/Preprocessor.cpp.s
.PHONY : Preprocessor.cpp.s

RegisterManager.o: RegisterManager.cpp.o
.PHONY : RegisterManager.o

# target to build an object file
RegisterManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/RegisterManager.cpp.o
.PHONY : RegisterManager.cpp.o

RegisterManager.i: RegisterManager.cpp.i
.PHONY : RegisterManager.i

# target to preprocess a source file
RegisterManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/RegisterManager.cpp.i
.PHONY : RegisterManager.cpp.i

RegisterManager.s: RegisterManager.cpp.s
.PHONY : RegisterManager.s

# target to generate assembly for a file
RegisterManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/RegisterManager.cpp.s
.PHONY : RegisterManager.cpp.s

ScratchAllocator.o: ScratchAllocator.cpp.o
.PHONY : ScratchAllocator.o

# target to build an object file
ScratchAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ScratchAllocator.cpp.o
.PHONY : ScratchAllocator.cpp.o

ScratchAllocator.i: ScratchAllocator.cpp.i
.PHONY : ScratchAllocator.i

# target to preprocess a source file
ScratchAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ScratchAllocator.cpp.i
.PHONY : ScratchAllocator.cpp.i

ScratchAllocator.s: ScratchAllocator.cpp.s
.PHONY : ScratchAllocator.s

# target to generate assembly for a file
ScratchAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/ScratchAllocator.cpp.s
.PHONY : ScratchAllocator.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compiler"
	@echo "... AArch64Instructions.o"
	@echo "... AArch64Instructions.i"
	@echo "... AArch64Instructions.s"
	@echo "... CodeGenerator.o"
	@echo "... CodeGenerator.i"
	@echo "... CodeGenerator.s"
	@echo "... ConstantFoldingPass.o"
	@echo "... ConstantFoldingPass.i"
	@echo "... ConstantFoldingPass.s"
	@echo "... DebugPrinter.o"
	@echo "... DebugPrinter.i"
	@echo "... DebugPrinter.s"
	@echo "... JitRuntime.o"
	@echo "... JitRuntime.i"
	@echo "... JitRuntime.s"
	@echo "... LabelManager.o"
	@echo "... LabelManager.i"
	@echo "... LabelManager.s"
	@echo "... Lexer.o"
	@echo "... Lexer.i"
	@echo "... Lexer.s"
	@echo "... LoopInvariantCodeMotionPass.o"
	@echo "... LoopInvariantCodeMotionPass.i"
	@echo "... LoopInvariantCodeMotionPass.s"
	@echo "... LoopOptimizer.o"
	@echo "... LoopOptimizer.i"
	@echo "... LoopOptimizer.s"
	@echo "... Optimizer.o"
	@echo "... Optimizer.i"
	@echo "... Optimizer.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... PassManager.o"
	@echo "... PassManager.i"
	@echo "... PassManager.s"
	@echo "... Preprocessor.o"
	@echo "... Preprocessor.i"
	@echo "... Preprocessor.s"
	@echo "... RegisterManager.o"
	@echo "... RegisterManager.i"
	@echo "... RegisterManager.s"
	@echo "... ScratchAllocator.o"
	@echo "... ScratchAllocator.i"
	@echo "... ScratchAllocator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

